all:
  children:

    swarm_manager:
      hosts:
        dev.diesel.net

  vars:
    ansible_user: automation
    ansible_python_interpreter: /usr/bin/python3

    signups_allowed: yes
    admin_token: admin
    
    diesel_host: bitwarden.dev.diesel.net
    kiwi_host: bitwarden.dev.kiwi-labs.net

