all:
  children:

    swarm_manager:
      hosts:
        tools.diesel.net

  vars:
    ansible_user: automation
    ansible_python_interpreter: /usr/bin/python3

    signups_allowed: yes
    admin_token: "{{ lookup('env', 'ADMIN_TOKEN') }}"
    
    diesel_host: bitwarden.diesel.net
    kiwi_host: bitwarden.kiwi-labs.net
