---

kind: pipeline
type: docker
name: Install Bitwarden (dev)

clone:
  depth: 1

steps:
  - name: deploy
    image: docker.nexus.diesel.net/drone-ansible:7.2.0
    settings:
      playbook: .ansible/deploy.yaml
      galaxy: .ansible/roles/requirements.yaml
      inventory: .ansible/inventories/dev.yaml
      private_key:
        from_secret: automation_id_rsa
trigger:
  branch:
    - development
  event:
    - push

---

kind: pipeline
type: docker
name: Install bitwarden (prod)

clone:
  depth: 1

steps:
  - name: deploy
    image: docker.nexus.diesel.net/drone-ansible:7.2.0
    environment:
      ADMIN_TOKEN:
        from_secret: admin_token
      YUBICO_CLIENT_ID:
        from_secret: yubico_client_id
      YUBICO_SECRET_KEY:
        from_secret: yubico_secret_key
    settings:
      playbook: .ansible/deploy.yaml
      galaxy: .ansible/roles/requirements.yaml
      inventory: .ansible/inventories/prod.yaml
      private_key:
        from_secret: automation_id_rsa

trigger:
  branch:
    - stable
  event:
    - push

...
