---

kind: pipeline
type: docker
name: Install Bitwarden (dev)

clone:
  depth: 1

steps:
  - name: deploy
    image: docker.nexus.diesel.net/drone-ansible:2.13
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
    settings:
      playbook: .ansible/deploy.yaml
      galaxy: .ansible/roles/requirements.yaml
      inventory: .ansible/inventories/dev
      private_key:
        from_secret: automation_id_rsa
trigger:
  branch:
    - development
  event:
    - push

---

kind: pipeline
type: docker
name: Install bitwarden (prod)

clone:
  depth: 1

steps:
  - name: deploy
    image: docker.nexus.diesel.net/drone-ansible:2.13
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      ADMIN_TOKEN:
        from_secret: admin_token
    settings:
      playbook: .ansible/deploy.yaml
      galaxy: .ansible/roles/requirements.yaml
      inventory: .ansible/inventories/prod
      private_key:
        from_secret: automation_id_rsa

trigger:
  branch:
    - stable
  event:
    - push

...
