# docker-compose.yaml

version: '3.8'
services: 


  main:
    image: vaultwarden/server:1.25.2
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
      - {{ data_dir }}:/data
    environment:
      - SIGNUPS_ALLOWED={{ signups_allowed | string | lower }}
      - ADMIN_TOKEN={{ admin_token }}
      - DOMAIN=https://{{ host }}
    deploy:
      labels:
        - traefik.enable=true

        # web interface
        - traefik.http.services.bitwarden-ui.loadbalancer.server.port=80
        - traefik.http.routers.bitwarden-ui.rule=Host(`{{ host }}`)
        - traefik.http.routers.bitwarden-ui.tls.certresolver=step-ca
        - traefik.http.routers.bitwarden-ui.service=bitwarden-ui
        
        # websocket notifications
        - traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012
        - traefik.http.routers.bitwarden-websocket.rule=Host(`{{ host }}`) && Path(`/notifications/hub`)
        - traefik.http.routers.bitwarden-websocket.tls.certresolver=step-ca
        - traefik.http.routers.bitwarden-websocket.service=bitwarden-websocket
        
    networks:
      - {{ traefik_network }}

networks:
  {{ traefik_network }}:
    external:
      name: {{ traefik_network }}
