- hosts: tools
  strategy: linear
  tasks:

    - include_role:
        name: common
        tasks_from: make_data_dir

    - include_role:
        name: docker
        tasks_from: stack_deploy
