# ansible-playbook deploy.yaml -i inventories/production/hosts --vault-id ~/.tokens/master_id

- hosts: tools
  strategy: linear
  tasks:

    - include_role:
        name: common
        tasks_from: make_data_dir

    - include_role:
        name: docker_deploy
